swagger: "2.0"
info:
  title: serverless-api-e5
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /serverless/sync/create-user:
    post:
      x-google-backend:
        address: https://us-central1-misw-4204-nube.cloudfunctions.net/create-user
      operationId: "create-user"
      summary: creates a new user
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: information required
          required: true
          schema:
            type: object
            properties:
              fullname:
                type: string
              username:
                type: string
              password:
                type: string
              role:
                type: string
              email:
                type: string
      responses:
        "201":
          description: user created
          schema:
            type: string

  /serverless/sync/login-user:
    post:
      x-google-backend:
        address: https://us-central1-misw-4204-nube.cloudfunctions.net/login-user
      operationId: "login-user"
      summary: creates a new token
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: information required
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        "200":
          description: token generated
          schema:
            type: string

  /serverless/sync/upload-video:
    post:
      x-google-backend:
        address: https://us-central1-misw-4204-nube.cloudfunctions.net/upload-video
      operationId: "upload-video"
      summary: creates a new video
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: description
          type: string
          description: video description
          required: true
        - in: formData
          name: token
          type: string
          description: user token
          required: true
        - in: formData
          name: video
          type: string
          format: binary
          description: The file to upload
          required: true
      responses:
        "200":
          description: token generated
          schema:
            type: string
