CREATE TABLE roles
(
    id          INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name   VARCHAR(100) NOT NULL,
    description VARCHAR(255) DEFAULT '',

    PRIMARY KEY (id)
);


CREATE TABLE users
(
    id       INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fullname VARCHAR(255)  NOT NULL,
    username VARCHAR(30)   NOT NULL,
    pass     VARCHAR(1000) NOT NULL,
    role_id  INTEGER       NOT NULL REFERENCES roles (id),
    email    VARCHAR(100) DEFAULT NULL,

    primary key (id)
);

ALTER TABLE users
    ADD CONSTRAINT users_unique UNIQUE (email);


CREATE TABLE videos
(
    id          INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(255) DEFAULT '',
    path        VARCHAR(500) NOT NULL,
    video_id    VARCHAR(100) DEFAULT NULL,
    user_id     INTEGER      DEFAULT NULL REFERENCES users (id),
    status      VARCHAR(500) DEFAULT '',
    timestamp   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);
